Required:
  GuildedBot_API_Token: ""
  VirusTotal_API_Token: ""
  Default_prefix: ";"
  Embed_Color: 0x02FA0F
  Timezone: American/New_York


Security:
  Mod_channel: "132a37a0-c3cc-420d-ac5b-8b89590ecdb9"

  Join_ban:
    - dl3Lx8B4

  Join_kick:
    - ""


Templates:
  Topic:
    - Hello! How are you?
    - What have you created that you are most proud of?
    - What's the best thing you got from one of your parents?
    - What bends your mind every time you think about it?
    - In your group of friends, what role do you play?
    - What incredibly strong opinion do you have that is completely unimportant in the grand scheme of things?
    - What's your favorite piece of clothing you own?
    - What fictional place would you most like to go to?
    - What's one place you've travelled that you never want to go back to?
    - When people come to you for help, what do they usually want help with?
    - What are you interested in that most people haven't heard of?
    - Mountains or ocean?
    - What was your best birthday?
    - Pizza or tacos?
    - What's the story behind one of your scars?
    - Pancakes or waffles?
    - Ice cream or chocolates?
    - Pirates or ninjas?
    - What was the best compliment you've ever received?
    - If you lost all of your possessions but one, what would you want it to be?
    - Who inspires you to be better?"
    - What dumb accomplishment are you most proud of?"
    - When was the last time you changed your opinion about something major?
    - What is something you can never seem to finish?
    - What is one of your favorite smells?
    - If you had to change your name legally, what would you change it to?
    - What are you a natural at?
    - What do you like most about your family?
    - Have you ever saved someone's life?
    - What's an unpopular opinion you have?
    - Who is one of your best friends, and what do you love about them?
    - Do you have any nicknames?
    - What's one of your favorite comfort foods?
    - What is your theme song?
    - What is one of the great values that guides your life?
    - What's your favorite book?
    - What's the last book you gave up on and stopped reading?
    - What's the worst movie you've ever seen?
    - What issue will you always speak your mind about?
    - What would you do on a free afternoon in the middle of the week?
    - Pet peeves?
    - What's the best piece of advice you ever received?
    - Who was your favorite teacher and why?
    - If you could have any superpower, what would it be and why?
    - What's on your bucket list this year?
    - If you could live in a book, TV show, or movie, what would it be?
    - What languages do you speak?
    - Would you rather be stuck on a broken ski lift or a broken elevator?
    - If you were a vegetable, what vegetable would you be?
    - What makes you cry?
    - Who are some of your heroes?
    - What's something you wish you'd figured out sooner?
    - What's your favorite candy?
    - What's your worst habit?
    - Favorite city?
    - What's your go-to dance move?
    - Do you ever sing when you're alone? What songs?
    - What's your earliest memory?
    - What's something you learned in the last week?
    - What story does your family always tell about you?
    - What talent would you show off in a talent show?
    - Will you rather take a risk even your life depends on it?
    - What’s the best part of your day so far?
    - Working on anything exciting at the moment? 
    - What do you have planned this weekend?
    - You won’t believe what just happened!
    - How would you describe yourself in 3 words? 
    - Would you choose a road trip or a resort vacation? 
    - What food are you craving right now? 
    - Unlimited money or unlimited time? 
    - What motivates you? 
    - What’s your astrological sign?
    - Who is your biggest role model?
    - What was your first concert? 
    - What are your top 5 bucket list activities?
    - What is something people do that drives you nuts?
    - What was your dream job as a kid?
    - What’s the most exciting thing you’ve read recently?
    - What do you love and hate about technology?
    - If you could time travel, what era would you revisit? 
    - What is something trendy that annoys you?

  8ball:
    - Yes
    - No
    - Maybe yes?
    - Maybe no?
    - I'm not sure, please try again
    - I don't know, ask google
    - Try again
    - IDK

  Punishment:
    - Pirates or ninjas?
    - No self pleasuring within 24hrs
    - Drink a water from a dirty sock